using System.Diagnostics.Metrics;

namespace JD.AI.Telemetry;

/// <summary>
/// Central <see cref="Meter"/> and instrument definitions for JD.AI metrics.
/// All counters and histograms follow the <c>jdai.*</c> naming convention and
/// use the emerging OpenTelemetry GenAI semantic conventions where applicable.
/// </summary>
public static class Meters
{
    /// <summary>Meter name for agent-level metrics.</summary>
    public const string AgentMeterName = "JD.AI.Agent";

    private static readonly Meter AgentMeter = new(AgentMeterName);

    /// <summary>Total number of agent turns completed.</summary>
    public static readonly Counter<long> TurnCount =
        AgentMeter.CreateCounter<long>(
            "jdai.agent.turns",
            unit: "turns",
            description: "Total number of agent turns completed.");

    /// <summary>Wall-clock duration of each agent turn in milliseconds.</summary>
    public static readonly Histogram<double> TurnDuration =
        AgentMeter.CreateHistogram<double>(
            "jdai.agent.turn_duration",
            unit: "ms",
            description: "Wall-clock duration of each agent turn.");

    /// <summary>Total tokens consumed across all providers (prompt + completion).</summary>
    public static readonly Counter<long> TokensUsed =
        AgentMeter.CreateCounter<long>(
            "jdai.tokens.total",
            unit: "tokens",
            description: "Total tokens consumed across all providers.");

    /// <summary>Number of tool invocations, broken down by tool name.</summary>
    public static readonly Counter<long> ToolCalls =
        AgentMeter.CreateCounter<long>(
            "jdai.tools.invocations",
            unit: "calls",
            description: "Number of tool invocations.");

    /// <summary>Number of provider errors (non-transient or after exhausting retries).</summary>
    public static readonly Counter<long> ProviderErrors =
        AgentMeter.CreateCounter<long>(
            "jdai.providers.errors",
            unit: "errors",
            description: "Number of provider errors after retry exhaustion.");

    /// <summary>Number of loop detection events (warnings and hard-stops).</summary>
    public static readonly Counter<long> LoopDetections =
        AgentMeter.CreateCounter<long>(
            "jdai.safety.loop_detections",
            unit: "events",
            description: "Number of tool loop detection events.");

    /// <summary>Number of circuit breaker trips.</summary>
    public static readonly Counter<long> CircuitBreakerTrips =
        AgentMeter.CreateCounter<long>(
            "jdai.safety.circuit_breaker_trips",
            unit: "trips",
            description: "Number of circuit breaker trip events.");

    /// <summary>Provider API call latency in milliseconds.</summary>
    public static readonly Histogram<double> ProviderLatency =
        AgentMeter.CreateHistogram<double>(
            "jdai.providers.latency",
            unit: "ms",
            description: "Provider API call latency.");

    // --- Gen AI semantic convention metrics ---

    /// <summary>Meter name for Gen AI metrics (follows OTel GenAI semconv).</summary>
    public const string GenAiMeterName = "JD.AI.GenAI";

    private static readonly Meter GenAiMeter = new(GenAiMeterName);

    /// <summary>Input (prompt) tokens consumed per LLM call.</summary>
    public static readonly Counter<long> GenAiInputTokens =
        GenAiMeter.CreateCounter<long>(
            "gen_ai.client.token.usage",
            unit: "tokens",
            description: "Number of input tokens consumed by Gen AI requests.");

    /// <summary>Output (completion) tokens generated per LLM call.</summary>
    public static readonly Counter<long> GenAiOutputTokens =
        GenAiMeter.CreateCounter<long>(
            "gen_ai.client.generation.tokens",
            unit: "tokens",
            description: "Number of output tokens generated by Gen AI responses.");

    /// <summary>Duration of Gen AI client operations in seconds.</summary>
    public static readonly Histogram<double> GenAiOperationDuration =
        GenAiMeter.CreateHistogram<double>(
            "gen_ai.client.operation.duration",
            unit: "s",
            description: "Duration of Gen AI client operations.");

    /// <summary>All meter names — pass to <c>.AddMeter()</c> when configuring OTel.</summary>
    public static readonly string[] AllMeterNames = [AgentMeterName, GenAiMeterName];
}
