{{- if .Values.config.secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jdai.fullname" . }}-secrets
  labels:
    {{- include "jdai.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.config.secretData | nindent 2 }}
{{- end }}
