// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace JD.AI.Specs.UI.Features.Dashboard
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "ui")]
    public partial class RoutingPageFeature : object, global::Xunit.IClassFixture<RoutingPageFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "ignore",
                "ui"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Dashboard", "Routing Page", "    As a gateway operator\n    I want to configure channel-to-agent routing rules\n" +
                "    So that incoming messages are directed to the correct AI agents", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "RoutingPage.feature"
#line hidden
        
        public RoutingPageFeature(RoutingPageFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
    #line hidden
#line 9
        await testRunner.GivenAsync("I am on the routing page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Dashboard/RoutingPage.feature.ndjson", 18);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Displays routing page heading", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Displays routing page heading")]
        [global::Xunit.TraitAttribute("Category", "smoke")]
        public async global::System.Threading.Tasks.Task DisplaysRoutingPageHeading()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Displays routing page heading", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 13
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 14
        await testRunner.ThenAsync("I should see the heading \"Channel → Agent Routing\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Sync OpenClaw button is available", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Sync OpenClaw button is available")]
        [global::Xunit.TraitAttribute("Category", "smoke")]
        public async global::System.Threading.Tasks.Task SyncOpenClawButtonIsAvailable()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Sync OpenClaw button is available", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 18
        await testRunner.ThenAsync("I should see the \"Sync OpenClaw\" button with sync icon", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Refresh button is visible", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Refresh button is visible")]
        public async global::System.Threading.Tasks.Task RefreshButtonIsVisible()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refresh button is visible", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 21
        await testRunner.ThenAsync("I should see the refresh button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Skeleton rows shown while loading", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Skeleton rows shown while loading")]
        public async global::System.Threading.Tasks.Task SkeletonRowsShownWhileLoading()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Skeleton rows shown while loading", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 25
        await testRunner.GivenAsync("the routing mappings are loading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
        await testRunner.ThenAsync("I should see 4 skeleton loading rows", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Routing data grid displays with correct columns", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Routing data grid displays with correct columns")]
        [global::Xunit.TraitAttribute("Category", "requires-routing")]
        public async global::System.Threading.Tasks.Task RoutingDataGridDisplaysWithCorrectColumns()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-routing"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Routing data grid displays with correct columns", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 31
        await testRunner.GivenAsync("there are routing mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
        await testRunner.ThenAsync("I should see the routing data grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
        await testRunner.AndAsync("the grid should have a \"Channel\" column", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
        await testRunner.AndAsync("the grid should have an \"Agent ID\" column", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
        await testRunner.AndAsync("the grid should have a \"Status\" column", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Channel column shows icon and name", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Channel column shows icon and name")]
        [global::Xunit.TraitAttribute("Category", "requires-routing")]
        public async global::System.Threading.Tasks.Task ChannelColumnShowsIconAndName()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-routing"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Channel column shows icon and name", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 38
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 39
        await testRunner.GivenAsync("there are routing mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
        await testRunner.ThenAsync("each routing row should display a channel icon", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 41
        await testRunner.AndAsync("each routing row should display the channel type name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Status chips show Override or Default", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Status chips show Override or Default")]
        [global::Xunit.TraitAttribute("Category", "requires-routing")]
        public async global::System.Threading.Tasks.Task StatusChipsShowOverrideOrDefault()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-routing"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Status chips show Override or Default", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 45
        await testRunner.GivenAsync("there are routing mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
        await testRunner.ThenAsync("rows with an assigned agent should show \"Override\" chip in primary color", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 47
        await testRunner.AndAsync("rows without an assigned agent should show \"Default\" chip", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Agent ID column is editable inline", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Agent ID column is editable inline")]
        [global::Xunit.TraitAttribute("Category", "requires-routing")]
        public async global::System.Threading.Tasks.Task AgentIDColumnIsEditableInline()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-routing"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Agent ID column is editable inline", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 50
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 51
        await testRunner.GivenAsync("there are routing mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
        await testRunner.ThenAsync("the Agent ID column should support inline cell editing", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Editing agent ID updates routing via API", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Editing agent ID updates routing via API")]
        [global::Xunit.TraitAttribute("Category", "requires-routing")]
        public async global::System.Threading.Tasks.Task EditingAgentIDUpdatesRoutingViaAPI()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-routing"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Editing agent ID updates routing via API", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 55
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 56
        await testRunner.GivenAsync("there are routing mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 57
        await testRunner.WhenAsync("I edit the agent ID on a routing row", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
        await testRunner.AndAsync("I commit the cell edit", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
        await testRunner.ThenAsync("a success snackbar should appear with \"Routing updated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Routing diagram section is displayed", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Routing diagram section is displayed")]
        [global::Xunit.TraitAttribute("Category", "requires-routing")]
        public async global::System.Threading.Tasks.Task RoutingDiagramSectionIsDisplayed()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-routing"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Routing diagram section is displayed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 63
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 64
        await testRunner.GivenAsync("there are routing mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 65
        await testRunner.ThenAsync("I should see the \"Routing Diagram\" section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 66
        await testRunner.AndAsync("the diagram should use a timeline layout", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Diagram shows channel-to-agent flow", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Diagram shows channel-to-agent flow")]
        [global::Xunit.TraitAttribute("Category", "requires-routing")]
        public async global::System.Threading.Tasks.Task DiagramShowsChannel_To_AgentFlow()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-routing"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Diagram shows channel-to-agent flow", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 69
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 70
        await testRunner.GivenAsync("there are routing mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
        await testRunner.ThenAsync("each timeline item should show a channel chip", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
        await testRunner.AndAsync("each timeline item should show an arrow", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
        await testRunner.AndAsync("each timeline item should show an agent chip or \"OpenClaw Default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Timeline items are color-coded by assignment", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Timeline items are color-coded by assignment")]
        [global::Xunit.TraitAttribute("Category", "requires-routing")]
        public async global::System.Threading.Tasks.Task TimelineItemsAreColor_CodedByAssignment()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-routing"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Timeline items are color-coded by assignment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 76
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 77
        await testRunner.GivenAsync("there are routing mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 78
        await testRunner.ThenAsync("timeline items with assigned agents should be primary colored", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 79
        await testRunner.AndAsync("timeline items using default should be default colored", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Sync OpenClaw triggers sync and shows snackbar", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Sync OpenClaw triggers sync and shows snackbar")]
        public async global::System.Threading.Tasks.Task SyncOpenClawTriggersSyncAndShowsSnackbar()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Sync OpenClaw triggers sync and shows snackbar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 82
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 83
        await testRunner.WhenAsync("I click the \"Sync OpenClaw\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
        await testRunner.ThenAsync("a success snackbar should appear with \"sync complete\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 85
        await testRunner.AndAsync("the routing data should refresh", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Channel icons match channel type", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Channel icons match channel type")]
        [global::Xunit.TraitAttribute("Category", "requires-routing")]
        public async global::System.Threading.Tasks.Task ChannelIconsMatchChannelType()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-routing"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Channel icons match channel type", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 89
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 90
        await testRunner.GivenAsync("there are routing mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 91
        await testRunner.ThenAsync("routing channel icons should match their type", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Page title is correct", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Page title is correct")]
        public async global::System.Threading.Tasks.Task PageTitleIsCorrect()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Page title is correct", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 94
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 95
        await testRunner.ThenAsync("the browser page title should be \"Routing — JD.AI\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Agent selector dropdown replaces free-text editing", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Routing Page")]
        [global::Xunit.TraitAttribute("Description", "Agent selector dropdown replaces free-text editing")]
        [global::Xunit.TraitAttribute("Category", "planned")]
        public async global::System.Threading.Tasks.Task AgentSelectorDropdownReplacesFree_TextEditing()
        {
            string[] tagsOfScenario = new string[] {
                    "planned"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Agent selector dropdown replaces free-text editing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 99
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await this.FeatureBackgroundAsync();
#line hidden
#line 100
        await testRunner.GivenAsync("there are routing mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 101
        await testRunner.WhenAsync("I click to edit an agent ID", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 102
        await testRunner.ThenAsync("a dropdown with available agents should appear", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
            }
        }
    }
}
#pragma warning restore
#endregion
