// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace JD.AI.Specs.UI.Features.Dashboard
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "ui")]
    public partial class SessionsPageFeature : object, global::Xunit.IClassFixture<SessionsPageFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "ui"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Dashboard", "Sessions Page", "    As a gateway operator\n    I want to view and manage conversation sessions\n   " +
                " So that I can monitor active conversations and review past ones", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SessionsPage.feature"
#line hidden
        
        public SessionsPageFeature(SessionsPageFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
    #line hidden
#line 8
        await testRunner.GivenAsync("I am on the sessions page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Dashboard/SessionsPage.feature.ndjson", 21);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Displays sessions page heading")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Displays sessions page heading")]
        [global::Xunit.TraitAttribute("Category", "smoke")]
        public async global::System.Threading.Tasks.Task DisplaysSessionsPageHeading()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Displays sessions page heading", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 13
        await testRunner.ThenAsync("I should see the heading \"Sessions\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Refresh button is visible")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Refresh button is visible")]
        public async global::System.Threading.Tasks.Task RefreshButtonIsVisible()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refresh button is visible", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 16
        await testRunner.ThenAsync("I should see the refresh button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Skeleton rows shown while loading")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Skeleton rows shown while loading")]
        public async global::System.Threading.Tasks.Task SkeletonRowsShownWhileLoading()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Skeleton rows shown while loading", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 20
        await testRunner.GivenAsync("the sessions list is loading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
        await testRunner.ThenAsync("I should see 5 skeleton loading rows", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Empty state when no sessions")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Empty state when no sessions")]
        public async global::System.Threading.Tasks.Task EmptyStateWhenNoSessions()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Empty state when no sessions", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 25
        await testRunner.GivenAsync("there are no sessions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
        await testRunner.ThenAsync("I should see the sessions empty state", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 27
        await testRunner.AndAsync("the empty state should display \"No sessions found\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Session data grid displays with correct columns")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Session data grid displays with correct columns")]
        [global::Xunit.TraitAttribute("Category", "requires-sessions")]
        public async global::System.Threading.Tasks.Task SessionDataGridDisplaysWithCorrectColumns()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Session data grid displays with correct columns", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 32
        await testRunner.GivenAsync("there are sessions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 33
        await testRunner.ThenAsync("I should see the sessions data grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
        await testRunner.AndAsync("the grid should have a \"Session ID\" column", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
        await testRunner.AndAsync("the grid should have a \"Model\" column", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
        await testRunner.AndAsync("the grid should have a \"Provider\" column", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
        await testRunner.AndAsync("the grid should have a \"Messages\" column", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
        await testRunner.AndAsync("the grid should have a \"Tokens\" column", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
        await testRunner.AndAsync("the grid should have a \"Status\" column", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
        await testRunner.AndAsync("the grid should have a \"Created\" column", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Session status chips display correctly")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Session status chips display correctly")]
        [global::Xunit.TraitAttribute("Category", "requires-sessions")]
        public async global::System.Threading.Tasks.Task SessionStatusChipsDisplayCorrectly()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Session status chips display correctly", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 43
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 44
        await testRunner.GivenAsync("there are sessions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 45
        await testRunner.ThenAsync("active sessions should show \"Active\" chip in green", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 46
        await testRunner.AndAsync("closed sessions should show \"Closed\" chip in default color", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Data grid supports filtering")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Data grid supports filtering")]
        [global::Xunit.TraitAttribute("Category", "requires-sessions")]
        public async global::System.Threading.Tasks.Task DataGridSupportsFiltering()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Data grid supports filtering", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 50
        await testRunner.GivenAsync("there are sessions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
        await testRunner.ThenAsync("the data grid should have filter controls", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Data grid supports sorting")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Data grid supports sorting")]
        [global::Xunit.TraitAttribute("Category", "requires-sessions")]
        public async global::System.Threading.Tasks.Task DataGridSupportsSorting()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Data grid supports sorting", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 55
        await testRunner.GivenAsync("there are sessions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
        await testRunner.WhenAsync("I click a column header", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
        await testRunner.ThenAsync("the grid should sort by that column", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Row action buttons are present")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Row action buttons are present")]
        [global::Xunit.TraitAttribute("Category", "requires-sessions")]
        public async global::System.Threading.Tasks.Task RowActionButtonsArePresent()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Row action buttons are present", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 62
        await testRunner.GivenAsync("there are sessions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
        await testRunner.ThenAsync("each session row should have a view button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
        await testRunner.AndAsync("each session row should have an export button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Active sessions have close button")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Active sessions have close button")]
        [global::Xunit.TraitAttribute("Category", "requires-sessions")]
        public async global::System.Threading.Tasks.Task ActiveSessionsHaveCloseButton()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Active sessions have close button", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 68
        await testRunner.GivenAsync("there are active sessions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
        await testRunner.ThenAsync("active session rows should have a close button in warning color", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Closed sessions do not have close button")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Closed sessions do not have close button")]
        [global::Xunit.TraitAttribute("Category", "requires-sessions")]
        public async global::System.Threading.Tasks.Task ClosedSessionsDoNotHaveCloseButton()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Closed sessions do not have close button", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 72
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 73
        await testRunner.GivenAsync("there are closed sessions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 74
        await testRunner.ThenAsync("closed session rows should not have a close button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="View session opens turn viewer")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "View session opens turn viewer")]
        [global::Xunit.TraitAttribute("Category", "requires-sessions")]
        public async global::System.Threading.Tasks.Task ViewSessionOpensTurnViewer()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View session opens turn viewer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 78
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 79
        await testRunner.GivenAsync("there are sessions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 80
        await testRunner.WhenAsync("I click the view button on a session", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
        await testRunner.ThenAsync("the turn viewer panel should appear below the grid", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
        await testRunner.AndAsync("the turn viewer should show \"Conversation:\" with the session ID", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Turn viewer displays conversation turns")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Turn viewer displays conversation turns")]
        [global::Xunit.TraitAttribute("Category", "requires-sessions")]
        public async global::System.Threading.Tasks.Task TurnViewerDisplaysConversationTurns()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Turn viewer displays conversation turns", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 85
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 86
        await testRunner.GivenAsync("there are sessions with turns", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 87
        await testRunner.WhenAsync("I click the view button on a session", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
        await testRunner.ThenAsync("each turn should show a role chip", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 89
        await testRunner.AndAsync("each turn should show message content", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
        await testRunner.AndAsync("each turn should show token counts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
        await testRunner.AndAsync("each turn should show response duration", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
        await testRunner.AndAsync("each turn should have a colored left border", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Turn viewer can be dismissed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Turn viewer can be dismissed")]
        [global::Xunit.TraitAttribute("Category", "requires-sessions")]
        public async global::System.Threading.Tasks.Task TurnViewerCanBeDismissed()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Turn viewer can be dismissed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 95
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 96
        await testRunner.GivenAsync("I am viewing a session\'s turns", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 97
        await testRunner.WhenAsync("I click the close button on the turn viewer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 98
        await testRunner.ThenAsync("the turn viewer should disappear", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Empty session shows no turns message")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Empty session shows no turns message")]
        [global::Xunit.TraitAttribute("Category", "requires-sessions")]
        public async global::System.Threading.Tasks.Task EmptySessionShowsNoTurnsMessage()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Empty session shows no turns message", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 101
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 102
        await testRunner.GivenAsync("there is a session with no turns", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 103
        await testRunner.WhenAsync("I click the view button on that session", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 104
        await testRunner.ThenAsync("the turn viewer should show \"No turns in this session\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Export session shows success snackbar")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Export session shows success snackbar")]
        [global::Xunit.TraitAttribute("Category", "requires-sessions")]
        public async global::System.Threading.Tasks.Task ExportSessionShowsSuccessSnackbar()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Export session shows success snackbar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 108
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 109
        await testRunner.GivenAsync("there are sessions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 110
        await testRunner.WhenAsync("I click the export button on a session", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 111
        await testRunner.ThenAsync("a success snackbar should appear with \"exported\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Close session shows success and refreshes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Close session shows success and refreshes")]
        [global::Xunit.TraitAttribute("Category", "requires-sessions")]
        public async global::System.Threading.Tasks.Task CloseSessionShowsSuccessAndRefreshes()
        {
            string[] tagsOfScenario = new string[] {
                    "requires-sessions"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Close session shows success and refreshes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 115
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 116
        await testRunner.GivenAsync("there are active sessions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 117
        await testRunner.WhenAsync("I click the close button on an active session", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 118
        await testRunner.ThenAsync("a success snackbar should appear with \"closed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 119
        await testRunner.AndAsync("the session list should refresh", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Page title is correct")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Page title is correct")]
        public async global::System.Threading.Tasks.Task PageTitleIsCorrect()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Page title is correct", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 122
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 123
        await testRunner.ThenAsync("the browser page title should be \"Sessions — JD.AI\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Filter sessions by agent, channel, and date range")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Sessions Page")]
        [global::Xunit.TraitAttribute("Description", "Filter sessions by agent, channel, and date range")]
        [global::Xunit.TraitAttribute("Category", "planned")]
        public async global::System.Threading.Tasks.Task FilterSessionsByAgentChannelAndDateRange()
        {
            string[] tagsOfScenario = new string[] {
                    "planned"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filter sessions by agent, channel, and date range", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 127
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 128
        await testRunner.GivenAsync("there are sessions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 129
        await testRunner.ThenAsync("I should see filter controls for agent, channel, and date range", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 130
        await testRunner.WhenAsync("I apply a filter", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 131
        await testRunner.ThenAsync("only matching sessions should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SessionsPageFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await SessionsPageFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
